# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_from_vent.ui'
#
# Created: Sun Sep  4 03:12:39 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form_vent(object):
    def setupUi(self, Form_vent):
        Form_vent.setObjectName("Form_vent")
        Form_vent.resize(416, 347)
        self.gridLayout = QtGui.QGridLayout(Form_vent)
        self.gridLayout.setObjectName("gridLayout")
        self.precio_vent = QtGui.QLineEdit(Form_vent)
        self.precio_vent.setEnabled(True)
        self.precio_vent.setReadOnly(True)
        self.precio_vent.setObjectName("precio_vent")
        self.gridLayout.addWidget(self.precio_vent, 9, 1, 1, 1)
        self.label_8 = QtGui.QLabel(Form_vent)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(Form_vent)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(Form_vent)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(Form_vent)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Form_vent)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.color = QtGui.QLineEdit(Form_vent)
        self.color.setMaxLength(50)
        self.color.setObjectName("color")
        self.gridLayout.addWidget(self.color, 5, 1, 1, 1)
        self.label = QtGui.QLabel(Form_vent)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.widget = QtGui.QWidget(Form_vent)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_aceptar = QtGui.QPushButton(self.widget)
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.horizontalLayout.addWidget(self.btn_aceptar)
        self.btn_cancel = QtGui.QPushButton(self.widget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.gridLayout.addWidget(self.widget, 11, 0, 1, 2)
        self.label_4 = QtGui.QLabel(Form_vent)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 9, 0, 1, 1)
        self.modelo = QtGui.QComboBox(Form_vent)
        self.modelo.setObjectName("modelo")
        self.gridLayout.addWidget(self.modelo, 2, 1, 1, 1)
        self.marca = QtGui.QComboBox(Form_vent)
        self.marca.setObjectName("marca")
        self.gridLayout.addWidget(self.marca, 1, 1, 1, 1)
        self.descuento = QtGui.QSpinBox(Form_vent)
        self.descuento.setPrefix("")
        self.descuento.setObjectName("descuento")
        self.gridLayout.addWidget(self.descuento, 8, 1, 1, 1)
        self.rut = QtGui.QComboBox(Form_vent)
        self.rut.setObjectName("rut")
        self.gridLayout.addWidget(self.rut, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Form_vent)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)
        self.patente = QtGui.QLineEdit(Form_vent)
        self.patente.setMaxLength(6)
        self.patente.setObjectName("patente")
        self.gridLayout.addWidget(self.patente, 4, 1, 1, 1)
        self.precio_lista = QtGui.QLineEdit(Form_vent)
        self.precio_lista.setReadOnly(True)
        self.precio_lista.setObjectName("precio_lista")
        self.gridLayout.addWidget(self.precio_lista, 6, 1, 1, 1)

        self.retranslateUi(Form_vent)
        QtCore.QMetaObject.connectSlotsByName(Form_vent)

    def retranslateUi(self, Form_vent):
        Form_vent.setWindowTitle(QtGui.QApplication.translate("Form_vent", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form_vent", "Rut", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form_vent", "Marca", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form_vent", "Modelo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form_vent", "Patente", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form_vent", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form_vent", "Precio de Lista", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_aceptar.setText(QtGui.QApplication.translate("Form_vent", "Aceptar", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("Form_vent", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form_vent", "Precio Venta", None, QtGui.QApplication.UnicodeUTF8))
        self.descuento.setSuffix(QtGui.QApplication.translate("Form_vent", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form_vent", "Desecuento", None, QtGui.QApplication.UnicodeUTF8))

