# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_modelo.ui'
#
# Created: Fri Aug 26 21:58:26 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_widget_modelo(object):
    def setupUi(self, widget_modelo):
        widget_modelo.setObjectName("widget_modelo")
        widget_modelo.resize(860, 710)
        self.gridLayout = QtGui.QGridLayout(widget_modelo)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtGui.QWidget(widget_modelo)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtGui.QLabel(self.widget_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.comboMarcas = QtGui.QComboBox(self.widget_2)
        self.comboMarcas.setObjectName("comboMarcas")
        self.horizontalLayout_6.addWidget(self.comboMarcas)
        self.btn_resetmarca = QtGui.QPushButton(self.widget_2)
        self.btn_resetmarca.setObjectName("btn_resetmarca")
        self.horizontalLayout_6.addWidget(self.btn_resetmarca)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.busca_modelo = QtGui.QLineEdit(self.widget_2)
        self.busca_modelo.setObjectName("busca_modelo")
        self.horizontalLayout_6.addWidget(self.busca_modelo)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 2)
        self.horizontalLayout_6.setStretch(2, 1)
        self.horizontalLayout_6.setStretch(3, 5)
        self.horizontalLayout_6.setStretch(4, 3)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        self.line = QtGui.QFrame(widget_modelo)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 3, 1)
        self.widget_4 = QtGui.QWidget(widget_modelo)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtGui.QLabel(self.widget_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.lbl_detalles = QtGui.QLabel(self.widget_4)
        self.lbl_detalles.setText("")
        self.lbl_detalles.setObjectName("lbl_detalles")
        self.verticalLayout_2.addWidget(self.lbl_detalles)
        self.label_7 = QtGui.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.lbl_descrip = QtGui.QLabel(self.widget_4)
        self.lbl_descrip.setText("")
        self.lbl_descrip.setObjectName("lbl_descrip")
        self.verticalLayout_2.addWidget(self.lbl_descrip)
        self.gridLayout.addWidget(self.widget_4, 0, 2, 3, 1)
        self.table_mod = QtGui.QTableView(widget_modelo)
        self.table_mod.setAlternatingRowColors(True)
        self.table_mod.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.table_mod.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_mod.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_mod.setSortingEnabled(True)
        self.table_mod.setObjectName("table_mod")
        self.gridLayout.addWidget(self.table_mod, 1, 0, 1, 1)
        self.widget_3 = QtGui.QWidget(widget_modelo)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtGui.QSpacerItem(509, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btn_agregamod = QtGui.QPushButton(self.widget_3)
        self.btn_agregamod.setObjectName("btn_agregamod")
        self.horizontalLayout_5.addWidget(self.btn_agregamod)
        self.btn_editamod = QtGui.QPushButton(self.widget_3)
        self.btn_editamod.setObjectName("btn_editamod")
        self.horizontalLayout_5.addWidget(self.btn_editamod)
        self.btn_borra_mod = QtGui.QPushButton(self.widget_3)
        self.btn_borra_mod.setObjectName("btn_borra_mod")
        self.horizontalLayout_5.addWidget(self.btn_borra_mod)
        self.gridLayout.addWidget(self.widget_3, 2, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(2, 1)

        self.retranslateUi(widget_modelo)
        QtCore.QMetaObject.connectSlotsByName(widget_modelo)

    def retranslateUi(self, widget_modelo):
        widget_modelo.setWindowTitle(QtGui.QApplication.translate("widget_modelo", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("widget_modelo", "Filtrar marca:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_resetmarca.setText(QtGui.QApplication.translate("widget_modelo", "Resetear", None, QtGui.QApplication.UnicodeUTF8))
        self.busca_modelo.setPlaceholderText(QtGui.QApplication.translate("widget_modelo", "Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("widget_modelo", "Imagen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("widget_modelo", "Detalles:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("widget_modelo", "Descripción:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_agregamod.setText(QtGui.QApplication.translate("widget_modelo", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_editamod.setText(QtGui.QApplication.translate("widget_modelo", "Ediar", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_borra_mod.setText(QtGui.QApplication.translate("widget_modelo", "Borrar", None, QtGui.QApplication.UnicodeUTF8))

