# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Wed Aug 24 18:47:33 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(623, 516)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_tab = QtGui.QTabWidget(self.centralwidget)
        self.main_tab.setGeometry(QtCore.QRect(0, 0, 621, 511))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_tab.sizePolicy().hasHeightForWidth())
        self.main_tab.setSizePolicy(sizePolicy)
        self.main_tab.setObjectName("main_tab")
        self.cliente_tab = QtGui.QWidget()
        self.cliente_tab.setObjectName("cliente_tab")
        self.tableWidget = QtGui.QTableWidget(self.cliente_tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 601, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.layoutWidget = QtGui.QWidget(self.cliente_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 10, 601, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.splitter_4 = QtGui.QSplitter(self.layoutWidget)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_4 = QtGui.QLabel(self.splitter_4)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtGui.QLineEdit(self.splitter_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.splitter_4)
        self.main_tab.addTab(self.cliente_tab, "")
        self.auto_tab = QtGui.QWidget()
        self.auto_tab.setObjectName("auto_tab")
        self.tableWidget_2 = QtGui.QTableWidget(self.auto_tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 50, 601, 421))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.layoutWidget1 = QtGui.QWidget(self.auto_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 601, 35))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtGui.QSplitter(self.layoutWidget1)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtGui.QLabel(self.splitter_2)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtGui.QComboBox(self.splitter_2)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.splitter_2)
        self.splitter_3 = QtGui.QSplitter(self.layoutWidget1)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_3 = QtGui.QLabel(self.splitter_3)
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtGui.QComboBox(self.splitter_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout.addWidget(self.splitter_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.splitter = QtGui.QSplitter(self.layoutWidget1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtGui.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.lineEdit = QtGui.QLineEdit(self.splitter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.splitter)
        self.main_tab.addTab(self.auto_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tab.setTabText(self.main_tab.indexOf(self.cliente_tab), QtGui.QApplication.translate("MainWindow", "Cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Marcas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Modelos", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tab.setTabText(self.main_tab.indexOf(self.auto_tab), QtGui.QApplication.translate("MainWindow", "Autos", None, QtGui.QApplication.UnicodeUTF8))

